### ISSUE TITLE
error permission denied

### ISSUE THREAD

**Issue by chennqqi** [fotomxq/coll-mz#1]
Error : open content/cache/738.jpg: permission denied
2016-12-09 09:09:48.972991817 +0800 CST  open content/coll-log/meizitu.log: permission denied

linux

**Comment by fotomxq** [comment]
（1）在采集过程中遇到，这个情况暂时无解（个人开发能力暂时不足）
所有采集器的基本采集顺序是：1、从URL下载到缓冲文件；2、计算该缓冲文件SHA1等信息；3、根据SHA1查询数据库，忽略采集过的文件；4、转移文件；5、写入数据库。
这个问题主要出在步骤2和4，所以还未记录到数据库，下次还会再次采集这个文件。
（2）在浏览数据的时候遇到。
这是因为获取图片是并发处理的，也就是说同一个文件有一定概率会同时访问到，系统锁死后出现权限异常。

感谢反馈，下一个版本会修改这些问题！

**Comment by buaazp** [comment]
遇到了同样的问题，@fotomxq 我估计你是在windows下开发的吧？你封装的file-operator里面没处理文件权限问题，把这儿改一下就行了：
https://github.com/fotomxq/coll-mz/blob/master/controller/file-operate.go#L39

```
//Write file
//If the file does not exist, it is created.
func WriteFile(src string, content []byte) error {
	return ioutil.WriteFile(src, content, 0644)
}
```
