### ISSUE TITLE
首页怎么并么有图片列表了；（编译，执行，访问xxx:8888 ,采集图片后）

### ISSUE THREAD

**Issue by wanminny** [fotomxq/coll-mz#2]
master branch...

**Comment by gyje** [comment]
编译文件的执行方式需要管理员权限，Ubuntu下加sudo，Windows右键管理员身份运行

**Comment by fotomxq** [comment]
1、采集后等待采集结束，或强制停止采集，然后再看首页就有图片了。主要用了sqlite，做这个的时候并没有搞定并发连接的问题，所以出了这档子错误。
其次是现在看来，第一代采集器大部分都已经失效了，首先煎蛋把URL规则修改了，去掉了开头的“http:/”，你可以修改一下代码确保其支持。其他采集我没有顾上检查，日后有时间会逐一修正。
2、编译文件并不需要管理员权限，我这边是win下开发的，普通用户下都可以正常编译。在ubuntu下可能是访问权限问题，所以需要管理员权限？建议你检查一下你的系统环境，应该和这个有关系。
唯一需要注意的是项目运行后，需要确保同一目录下的文件权限。

**Comment by gyje** [comment]
@fotomxq 需要管理员权限运行才能写入图片，不是编译。

**Comment by fotomxq** [comment]
这个就是目录修改权限的问题，我是在win下开发的，所以在linux上部署需要考虑到运行目录的权限，否则会出现各种问题。因为golang中修改文件时，如果参数不指定权限会自动要求很高的权限，我当时开发的时候没考虑到这个问题。
你可以试试给予项目目录644、777权限，这个只需要特定目录写入和读取权限就可以。
